format_version: 10
pipelines:
  miscellaneous-code-tools-terraform:
    group: tools
    label_template: "${COUNT}"
    materials:
      ansible:
        git: https://github.com/Priya-Devops2023/miscellaneous-code.git
        shallow_clone: false
        auto_update: true
        branch: main
        includes:
          - src/**/*.*
    stages:
      - apply:
          fetch_materials: true
          jobs:
            apply:
              timeout: 0
              tasks:
                - exec:
                    command: terraform
                    arguments: ["init"]

                - exec:
                    command: terraform
                    arguments: ["apply", "-auto-approve"]
                    working_directory: prometheus
